name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

    #   - name: Run unit tests
    #     run: npm run test

    #   - name: Install Playwright browsers
    #     run: npx playwright install --with-deps

      - name: Build the project
        run: npm run build

    #   - name: Start Vite preview
    #     run: nohup npm run preview -- --port 4173 &

    #   - name: Wait for preview to start
    #     run: sleep 5

    #   - name: Run Playwright tests
    #     run: npm run test:e2e

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
